### ISSUE TITLE
Exercise 4 - use ternary operator, format code

### ISSUE THREAD

**Issue by mensur-durakovic** [zeljkotopic/op_vjezbe#1]
Instead of this:

```
if (br == 3)
    return 3;
else
    return 0;
```

we can use ternary operator. Please refactor this, format your code and delete unecessaty empty lines and whitespaces. Rest is ok 😉

**Comment by zeljkotopic** [comment]
I will fix it and push it again,thank you for review.

sub, 11. tra 2020. 15:40 Mensur Duraković <notifications@github.com> je
napisao:
